server:
  port: 10550

spring:
  data:
    mongodb:
      host: ec2-18-218-144-241.us-east-2.compute.amazonaws.com
#      port: 27017
      database: retoml
      uri: mongodb://ec2-18-218-144-241.us-east-2.compute.amazonaws.com/retoml
rest:
  controller:
    path:
      principal: /coupon
      stats: /stats
    top-favorites: 5
api:
  ml:
    url:
      base: https://api.mercadolibre.com
      items: /items